export const GET_DATA_REQUEST = "GET_PRIVATE_DATA_REQUEST";
export const POST_IMAGE = "POST_IMAGE";

export const GET_PRIVATE_DATA_SUCCESS = "GET_PRIVATE_DATA_SUCCESS";
export const GET_PUBLIC_DATA_SUCCESS = "GET_PUBLIC_DATA_SUCCESS";
export const GET_SCOPED_DATA_SUCCESS = "GET_SCOPED_DATA_SUCCESS";
export const GET_IMAGE_DATA_SUCCESS = "GET_IMAGE_DATA_SUCCESS";

export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
