export const GET_DATA_REQUEST = "GET_PRIVATE_DATA_REQUEST";

export const GET_PRIVATE_DATA_SUCCESS = "GET_PRIVATE_DATA_SUCCESS";
export const GET_PUBLIC_DATA_SUCCESS = "GET_PUBLIC_DATA_SUCCESS";
export const GET_SCOPED_DATA_SUCCESS = "GET_SCOPED_DATA_SUCCESS";
export const GET_ADMIN_DATA_SUCCESS = "GET_ADMIN_DATA_SUCCESS";

export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const POST_IMAGE = "POST_IMAGE";
export const POST_PARAGRAPH = "POST_PARAGRAPH";
export const POST_ARTICLE = "POST_ARTICLE";

export const CLEAR_ARTICLE_FORM = "CLEAR_ARTICLE_FORM";
export const SHOW_ADD_PARAGRAPH = "SHOW_ADD_PARAGRAPH";
export const SHOW_ADD_IMAGE = "SHOW_ADD_IMAGE";
