export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const POST_IMAGE = "POST_IMAGE";

export const GET_PRIVATE_DATA_SUCCESS = "GET_PRIVATE_DATA_SUCCESS";
export const GET_PUBLIC_DATA_SUCCESS = "GET_PUBLIC_DATA_SUCCESS";
export const GET_SCOPED_DATA_SUCCESS = "GET_SCOPED_DATA_SUCCESS";
export const GET_ADMIN_DATA_SUCCESS = "GET_ADMIN_DATA_SUCCESS";

export const CLEAR_PRIVATE_DATA = "CLEAR_PRIVATE_DATA";
export const CLEAR_PUBLIC_DATA = "CLEAR_PUBLIC_DATA";
export const CLEAR_SCOPED_DATA = "CLEAR_SCOPED_DATA";
export const CLEAR_ADMIN_DATA = "CLEAR_ADMIN_DATA";

export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
export const CLEAR_DATA_FAILURE = "CLEAR_DATA_FAILURE";
